
INSERT INTO MEDICINE (MEDICINE_ID, NAME, PRICE, CATEGORY, ACTIVE)
VALUES (1, 'Paracetamol', 2.5, 'Tablet', 1);

INSERT INTO MEDICINE (MEDICINE_ID, NAME, PRICE, CATEGORY, ACTIVE)
VALUES (2, 'Amoxicillin', 5.0, 'Capsule', 1);

delete from inventory;
INSERT INTO INVENTORY (MEDICINE_ID, BATCH_NO, EXPIRY_DATE, QUANTITY)
VALUES (1, 'PARA-B1', TO_DATE('2026-06-30','YYYY-MM-DD'), 100);
INSERT INTO INVENTORY (MEDICINE_ID, BATCH_NO, EXPIRY_DATE, QUANTITY)
VALUES (2, 'AMOX-B1', TO_DATE('2025-12-31','YYYY-MM-DD'), 100);
INSERT INTO INVENTORY (MEDICINE_ID, BATCH_NO, EXPIRY_DATE, QUANTITY)
VALUES (2, 'AMOX-B2', TO_DATE('2026-12-31','YYYY-MM-DD'), 50);
commit;

-- Example: Sell 5 Paracetamol + 10 Amoxicillin with 10% discount
DECLARE
    v_meds SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(1, 2);  -- Medicine IDs
    v_qtys SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(5, 10); -- Quantities
BEGIN
    ADD_SALE(v_meds, v_qtys, 10); 
END;
/

-- Check results
SELECT * FROM SALES;
SELECT * FROM SALES_DETAILS;
SELECT * FROM INVENTORY;

DECLARE
    v_meds SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(2);  -- Medicine IDs
    v_qtys SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(100); -- Quantities
BEGIN
    ADD_SALE(v_meds, v_qtys, 10); 
END;
/
